name: CD checks

on:
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Run bundle install
        run: bundle config set --local only default ci && bundle install

      - name: Run rake cd
        run: rake cd
